baseURL = "https://seattle-plastics-test.onrender.com"
languageCode = "en-us"
title = "Seattle Plastics"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "We have perfected custom manufacturing at stock prices"
    meta_og_title = "Seattle Plastics"
    meta_og_type = "website"
    meta_og_url = "https://seattle-plastics-test.onrender.com"
    meta_og_description = "Seattle Plastics"

[[menu.main]]
name = "Home"
url = "https://seattle-plastics-test.onrender.com"
weight = 1

[[menu.main]]
name = "Services"
url = "https://seattle-plastics-test.onrender.com/services"
weight = 2 

[[menu.main]]
name = "Contact"
url = "https://seattle-plastics-test.onrender.com/contact"
weight = 3 

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
