baseURL = "http://www.seattleplastics.com"
languageCode = "en-us"
title = "Seattle Plastics"
themesDir = "themes"
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "We have perfected custom manufacturing at stock prices"
    meta_og_title = "Seattle Plastics"
    meta_og_type = "website"
    meta_og_url = "http://www.seattleplastics.com"
    meta_og_description = "Seattle Plastics - We have perfected custom manufacturing"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
